services:
  - type: web
    name: football-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn proxy_apifootball:app --host 0.0.0.0 --port 10000
    envVars:
      - key: APIFOOTBALL_KEY
        value: 30e1e48fbc6d0839f42212185149c7b4
      - key: PROXY_TOKEN
        value: CF_Proxy_2025_Secret_!@#839
