services:
  - type: web
    name: football-proxy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn proxy_apifootball:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: APISPORTS_KEY
        sync: false
      - key: PROXY_TOKEN
        sync: false
